### ISSUE TITLE
Don't add link when sharing from an app. Android

### ISSUE THREAD

**Issue by uGeek** [floccusaddon/floccus#1014]
### Describe the bug
When you share a link from a browser or RSS application with floccus, the application receives the link, sometimes, depending on the source application, the title and link appear in the link area of floccus. Still correcting this error, floccus does not add the link.

This only happens in the share option. If you add it manually, floccus works perfectly.

Congratulations on the application, it is fantastic.

I synchronize my bookmarks between my desktop with Firefox and Android with my WebDAV server.

Thanks a lot.
Angel

**Comment by gitmaker032** [comment]
I have the same problem. The link is not added to anything when I'm share it to Floccus. Also, there is no way to select a subfolder to save, and it's impossible to save the bookmark to the root. It would be great if when adding a bookmark via Share screen you could choose the saving path (subfolder). Also, the last selected subfolder should be saved for later actions so that there is no need to select it again later.

**Comment by marcelklehr** [comment]
Thanks for reporting this! I've been able to fix the problem and will implement folder selection (as well as the ability to move items) soon.

> Also, the last selected subfolder should be saved for later actions so that there is no need to select it again later.

@gitmaker032 great suggestion!
