### ISSUE TITLE
Only mobile bookmarks syncing on kiwi

### ISSUE THREAD

**Issue by badochov** [floccusaddon/floccus#1027]
### Describe the bug
I use nextcloud account, syncing between desktop browsers works flawlessly. Though when I try to use it in kiwi only mobile bookmarks folder gets synced.

### To Reproduce
1. Install kiwi
2. Install floccus on kiwi
3. Login woth nextcloud
4. Try to sync

### Expected behavior
All other bookmarks should be synced as well.

### Screenshots
![Screenshot_2022-01-31-04-20-59-945_com kiwibrowser browser](https://user-images.githubusercontent.com/26444395/151734574-98d43ac2-7ca5-407b-9751-622d6213be15.jpg)

### Desktop
(please complete the following information)
 - OS: Android
 - Browser Kiwi
 - Browser Version 98.0.4758.66
 - Floccus version: 4.9.0
 - Floccus sync method: nextcloud bookmarks

### Server
(please complete the following information)
I use nch.pl as my provider. Unfortunately, I wasnt able to find any more information than:
- Nextcloud version: 23.0.0.10

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
Unfortunately I dont see any button.

- [ ] Debug log provided

**Comment by sevmonster** [comment]
Use the **Mobile bookmarks** folder as the root.

If I recall: Chromium does not allow you to create items in the toplevel root folder (**/**), that space is reserved for special folders like *Mobile bookmarks*, *Bookmarks bar*, *Other bookmarks*. Any attempts by floccus to create items inside the root folder (whether in Kiwi or on any other Chromium browser) will fail. The intention is that Google Sync or some other native browser process will create and manage these folders, so it's by design that extensions are not able to write to it.

**Comment by marcelklehr** [comment]
@sevmonster Thanks for the nicely written answer, I took the liberty to post it on floccus.org/faw :)
