### ISSUE TITLE
Cannot connect floccus android 4.9 to nextcloud (non-public CA)

### ISSUE THREAD

**Issue by thsnielsen** [floccusaddon/floccus#1038]
### Describe the bug
When i enter my connection details, i get E017 Network error (well it is in french so it may be differently worded ..)

### To Reproduce
install floccus app from playstore, configure account details (i can share not in public)
I enter the server url, user name, and password, save, and see error E017 Network error in yelow on the main screen

### Desktop
(please complete the following information)
 - OS: android 12
 - Browser no Browser - it is about the android app
 - Floccus version: 4.9
 - Floccus sync method: nextcloud
 
### Server
 - OS: raspbian bullseye
 - Nextcloud version: 23
 - Bookmarks app version: 10.0.3

### Debug log
not sure howto provide a debug log with the android app - if it is possible please advise

### Additional context
I hope you have read all the way here, because i have some suspicions.
I use my own certificate authority, properly created (root, intermediate CA, CA, Server certificate. no funky algorithms selected, just not a public trusted root CA. I CAN connect to nextcloud using https, and the floccus 4.10 plugin for firefox 96.0.3 works fine. I also connect to the nextcloud server from the nextcloud app on my phone. There seem to be missing the "trust this server anyway" option ;-)

**Comment by thsnielsen** [comment]
> ok so i generated a new certificate, installed on the nextcloud server, and can OK connect to it from the phone and web, and the floccus 4.10 firefox plugin also connects. Then i verified that my CA is in the phone, but the situation stays E017. Bear in mind that when i import a CA to android 12, it is located in the USER CA store in android and not in the system CA store. I seem to remember that the apps has to look also in the user CA store?

this is my checklist if you want to try it out. it is all there in a few pages to have your own CA, intermediate and server cert
: https://jamielinux.com/docs/openssl-certificate-authority/introduction.html

**Comment by mnalis** [comment]
@thsnielsen tangentially related - after reading your introduction about needing to pay to Verisign/Digicert CA to get your cert signed...  Are you aware of free CAs like https://letsencrypt.org/ and similar?

Those are not only free of charge and trusted globally (so no need for manually installing your own CA on each client), but opensource ACME-protocol tools completely automate the certificate renewals, and it is much simpler than installing your own CA.  (of course, there might be other reasons for preferring your own CA, but I'd though to give you heads-up if you were not aware, and/or wish to update your docs).

**Comment by thsnielsen** [comment]
Thank you for your thoughts! I chose to use my own CA explicitly to have the CA in my possession. Long time ago I was so much told not to just use a self signed certificate on the one hand (though noone was able to give me a valid technical reason why)  and on the other hand about government  backdoors to the publicly trusted roots (no technical reason either other than imagining they are badly salt'ed). But in the end i got a taste for using my own CA and then there is no more discussion. 
So that is my just my case, but i imagine also quite some small medium size enterprises, that would need their own CA also to rule out any dependency.

**Comment by thsnielsen** [comment]
I really appreciate the exchanges here.
 - Onto the comments.
I tried both importing the full chain and only the trusted root. 
The trusted root imports to the user certificates (yes! ;-) and when i try to import the full chain instead  (that displays correctly in firefox if i inspect the certificate i see three tabs as if you see with the certificate of amazon.com (certificate, intermediateCA, CA) only difference is that firefox moans about mine because the issuer is unknown which is true), importing full chain get a message saying i need also to import the private key (so importing the full chain seems destined for another use case). I googled a bit, and it looks like it is by design that you can only import trusted root and then every issued cert by it is trusted, and also that the user cannot import to the system trusted root store (Android 12 non-rooted).

**Comment by sevmonster** [comment]
I came to the same conclusions. So it seems it may not be possible without root to get all apps to trust a CA or cert.

The other option is to [build using your own security config](https://developer.android.com/training/articles/security-config), but floccus uses Capacitor to wrap the webapp in an [Android WebView or Chrome Custom Tab](https://capacitorjs.com/docs/android#android-support)... so I don't know that it would work to enable it on the floccus app itself since it won't be handling the connection. I would think the WebView/Chrome app would need to be set up for it, and on most devices those apps cannot be replaced without root either. In addition, searching the [Capacitor docs](https://capacitorjs.com/docs/) for "certificate" and "signed" did not bear fruit, so I imagine it may not be possible to configure your own cert for it.

On what certs the device trusts, I finally found the info I was initially looking for; I used the SO answer because it was all I could find at the time. See [here](https://developer.android.com/training/articles/security-config#CustomTrust):

>By default, secure connections (using protocols like TLS and HTTPS) from all apps trust the pre-installed system CAs, and apps targeting Android 6.0 (API level 23) and lower also trust the user-added CA store by default. An app can customize its own connections using base-config (for app-wide customization) or domain-config (for per-domain customization).

See also: https://stackoverflow.com/questions/40349141

>thank you for taking your time to reply so richly

Thank *you*. I just thought your comments were interesting and wanted to give some context. Aside from issues like this, private CAs are definitely a good idea (and much better than self signed)

**Comment by marcelklehr** [comment]
Have you tried the System CA store as well? User CA store seems to only work on Android 6.0 and lower, from what I've read.

Capacitor sadly does not expose onReceivedSslError on their WebViewListener interface, which would allow building some kind of exception setting for floccus. I'll open a ticket with them :)

**Comment by sevmonster** [comment]
> Have you tried the System CA store as well? User CA store seems to only work on Android 6.0 and lower, from what I've read.

That's the problem, you cannot add to system store on Android 12 as far as anyone here has seen.

> Capacitor sadly does not expose onReceivedSslError on their WebViewListener interface, which would allow building some kind of exception setting for floccus. I'll open a ticket with them :)

It would be nicer if they came up with a way to support user-provided certs explicitly, or to confirm if building with security configs could affect the web views (I imagine it wouldn't). But that's good too!

**Comment by arkdae** [comment]
What's the status of this bug? I just installed Floccus on my Android phone and I'm getting this same error. I am using a Letsencrypt signed certificate, and all of my other Nextcloud programs are running fine and properly accessing my server.

**Comment by sevmonster** [comment]
> I wonder if it is not saving the password. When I click on the gear icon, the password field is always blank. I can't tell if it is just a security feature or if it is indeed not saving the password.

That is intentional. The field is not filled with anything when you edit.

What Android version are you on and when is the last time you updated? Modern devices should include the new LE CA.

**Comment by arkdae** [comment]
Android version 9, patch level May 1, 2019. There are no more updates for this phone.

I question why you question the cert chain. How is it possible that all my other Nextcloud software works fine, but this does not? I'm reasonably confident that the certs are installed properly.

**Comment by arkdae** [comment]
I found the "Trusted Credentials" section of Android settings. I do not see "Let's Encrypt" under the system tab. I don't have any certs under the user tab. I do see "ISRG Root X1," Let's Encrypt's issuer. I can connect to my Nextcloud server through Firefox on my phone, and it doesn't complain about the cert. I'm not sure if Firefox is using the system cert store. I would hope it is.

Is it possible other programs are fine since Let's Encrypt's cert is signed by ISRG and they're not concerned about the entire cert chain, but Floccus is?

**Comment by arkdae** [comment]
Okay, I specifically installed the Let's Encrypt R3 CA as a user credential. But that did not fix it.

**Comment by sevmonster** [comment]
Let's Encrypt moved off of the old R3/R4 intermediates signed by the original DST Root CA X3 in 2020, and they expired in 2021. Based on what I am reading Android 9 should have the new ISRG roots as you can see, it was added starting with Android 7. New LE intermediates should be trusted by your system.

> I'm not sure if Firefox is using the system cert store. I would hope it is.

Firefox likes to download its own certificate bundle. Not sure about Android.

> I question why you question the cert chain.

Because the easiest way to get certificate issues resolved is to import the root CA and any intermediate certs to the system store. This makes all of them trusted regardless of other factors. But as we have seen that is no longer easily accomplished with modern Android.

In any case, it does look like your device should support the newest LE CA. Your problem is likely not related to this issue. Importing the intermediates (which should be trusted already) probably won't help, unless your LE cert is using an expired intermediate somehow. Android ignores the expiry date of trust anchors.

**Comment by arkdae** [comment]
I see the problem. It was my misunderstanding. I did not realize that I needed to have the Nextcloud Bookmarks add-on installed. I thought this tool just used Nextclouds file synchronization mechanism in some way. When I went to create a new bug report, I saw it asking me what version of Nextcloud Bookmarks I'm using, which clued me in to what I needed. After enabling that, it is working now.

**Comment by marcelklehr** [comment]
I'm closing this as SSL is out of scope of floccus. If android doesn't allow this there's nothing I can do.
