### ISSUE TITLE
Popup window clipped / cropped/ cut off, when used with Firefox overflow menu

### ISSUE THREAD

**Issue by exekutive** [floccusaddon/floccus#108]
I have Floccus in the Firefox overflow menu. When I click the Floccus icon, it only shows me half the interface window. The edge of the browser window seems to cut off the right half of it, so that I can't see all the text boxes and buttons.

Firefox 60
Floccus 2.2.3

**Comment by marcelklehr** [comment]
Did you click on the floccus symbol directly or by first clicking on some 'show more' button? If I resize my window to be really small so that a 'show more' button appears I get a similar result, where the pop over actually has enough room, but the right quarter is blank. I suspect there's something wrong in firefox :/

**Comment by exekutive** [comment]
nope, just the regular toolbar icon

**Comment by marcelklehr** [comment]
Would you be able to provide a screenshot of this? (with sensitive data removed, of course)

**Comment by exekutive** [comment]
Hmm. I installed the extension again. Floccus is still cut off, but now there are scroll bars, which I didn't get before. It's better, but obviously it would be better if the window were displayed in its entirety.
![screen shot 2018-06-02 at 16 46 35](https://user-images.githubusercontent.com/4755215/40881776-d03e4be4-6684-11e8-9fa6-4c92cb8a97cc.png)

**Comment by marcelklehr** [comment]
Yup, that's the bug in firefox that I referenced. As a short-term solution, you can move the floccus icon out of the menu and place it directly into the toolbar if that's possible.

**Comment by brainchild0** [comment]
It's sad  that after three years since  [Firefox issue 1373490](https://bugzilla.mozilla.org/show_bug.cgi?id=1373490) was opened, the most recent activity was    knocking it to a _lower_ priority.


Could we change the title of this issue? If it had the word "cropped" or "clipped', then I would have discovered it myself in the search. Also since the appearance is correct when not in the the overflow menu, this detail might be added. (E.g. "Popup window clipped, used with overflow menu".)

**Comment by brainchild0** [comment]
@marcelklehr: Just a thought, since triage is often determined by perceptions of number of affected users, perhaps you, might  make some noise in the Firefox discussion, if you haven't already, representing yourself as an extension developer, and explaining the difficulties and the lack of an effective workaround.

**Comment by pinpontitit** [comment]
Is this issue still up to date ?

**Comment by brainchild0** [comment]
The original symptoms continue to reproduce, and the upstream bug remains open.
