### ISSUE TITLE
Sync to local file

### ISSUE THREAD

**Issue by joaoherberto** [floccusaddon/floccus#1086]
### Describe the feature you'd like to request

Configure floccus to sync to a local file/directory which Syncthing will then synchronize to other devices?

### Describe the solution you'd like

First, I am using floccus with a Webdav disk and it works perfectly. 

I also use KeepassXC with the browser extensions to sync my passwords and I use Syncthing to continually sync the KeepassXC file. Everytime it changes, KeepassXC reloads the file. It works flawlessly.

Is there a way to configure floccus to sync to a local file/directory which Syncthing will then synchronize to other devices?

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
Yes, there is :) See https://github.com/TCB13/LoFloccus#readme

**Comment by joaoherberto** [comment]
Nice but sadly not available for Linux, it would be nicer not to have another extension. I don't want to offend anyone, because I know very little about programming, is it that difficult to add the option for a local directory?

**Comment by marcelklehr** [comment]
> Nice but sadly not available for Linux

Yes, that's an ongoing discussion. Web Extensions are not allowed to access your files directly, which is why floccus doesn't support this out of the box. As far as I am aware, it is still possible to build LoFloccus it yourself, but I understand that's not everbody's cup of tea. An alternative is to simply set up some other WebDAV server on your local machine, e.g. something like this: https://github.com/marlluslustosa/Floccus-WebDavDocker
