### ISSUE TITLE
[Android] Disable splash screen

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1130]
### Describe the feature you'd like to request

Papercut issue.

Splash screen is always shown when accessing the app.  Is it necessary or is their an option to disable it?  Loosely related to #1130 

### Describe the solution you'd like

Skip showing the splash screen when browsing back to the app and just go directly to bookmarks

### Describe alternatives you've considered

Unsure

**Comment by pinpontitit** [comment]
By "splash screen", you mean the very first screen, showing the blue Floccus icon, just before the bookmarks ?
The kind of screen that appears while the app is loading the first time you open it ?

Thank you for teaching me that it existed because frankly I never noticed it.

How it works on my phone:

When I click on an app, for example Gmail app, or Tutanota app, or whatever:
As I have Android animations activated, the app icon grows and goes in the center of the screen.

So when I click on Gmail, all the screen becomes black and the gmail icon is at the center of the screen, and its written "Google workspace" below.
After not even 1 second of load, this black screen with Gmail icon disappear, and I can see my emails.

But when the Gmail app is running in background, if I click on it again, this "splash screen" doesnt happen. It only appears when i run the app the first time.

When I click on Tutanota, same thing: a white screen with a slightly bigger Tutanota Icon in the middle. Then after not even 1 second, I can see the log-in page.
However, as for Gmail, if the app is already running I don't see this "splash screen"

But on Floccus, there's **two** "splash screen".
The first splash screen is **black** with the Floccus icon at the center. 
This first screen is similar to the Gmail and Tutanota ones for example.
I guess this is some automatic Material Design behavior.
This first screen is "beautifully" made. I mean, its not ugly and fits well with android behavior.

But after this first screen, there's a **second** "splash screen" !
This time its **white** with a smaller and ill-sized (=the proportions are not respected) floccus icon at the center.

I don't see the reason for this second splash screen, and its kind of ugly, it doesnt fit well in Android.
The icon proportions are incorrect, and having two subsequents splash screen looks unprofessional, as if the app wasnt "Native" but kind of "PWA" (maybe its the case).

However those two "splash screens" only happens the first time I run Floccus, if its running in backgroung it doesnt happen anymore.

So, to conclude:
If you are speaking about this second splash screen, I agree with you, its unnecessary, ugly, and it increases the loading time by some milliseconds.

However that's not big deal, just aesthetic considerations.
