### ISSUE TITLE
Android: "create folder" option when adding new bookmark

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1138]
### Describe the feature you'd like to request

Hi
I wish you could add this feature one day if its not too difficult to implement.

When I want to bookmark an interesting website with Floccus on Android: while on my browser I click on "Share" > "Floccus".

Then Floccus app opens, and a popup appears with three rows:
-Title
-Link
-Parent folder

If I click on the "folder" icon next to the Parent folder row, I can see all my folders.
But I cant create a new folder.

If I want to, I have to exit this popup, or save the bookmark on the wrong folder, then go to the main page and click on the "+" icon > add folder.
And only after I can Edit the bookmark I just added to put it in this new folder.

Thats a waste of time.

thanks

### Describe the solution you'd like

...

### Describe alternatives you've considered

...

**Comment by pinpontitit** [comment]
I wasn't able to run floccus in Android Studio (I'll give more details to you later) so I couldn't check if my code works.

But, does adding this code:

<v-btn
     v-model="fab"
     fixed
     bottom
     right
     color="blue darken-1"
     dark
     fab
     small
     @click="addFolder">
          <v-icon>
              mdi-plus
          </v-icon>
</v-btn>

to  DialogChooseFolder.Vue  could solve this ?

**Comment by marcelklehr** [comment]
It would take a bit more than this. addFolder is only defined in Tree.vue and is not callable from DialogChooseFolder, also DialogEditFolder needs to be added to the template in order to be able to get displayed. Calling addFolder causes a boolean flag in data() to be set which allows DialogEditFolder to be displayed, which can then add a folder. Ideally the new folder would then be directly selected by the folder chooser.

**Comment by pinpontitit** [comment]
ok thanks for the details. I'll investigate until I'm happy with something
