### ISSUE TITLE
Beter tab sync (suggestion on how it should work)

### ISSUE THREAD

**Issue by hellomiakoda** [floccusaddon/floccus#1200]
### Describe the feature you'd like to request

The ability to sync open tabs directly to a local bookmark subfolder - see "solution" for why

### Describe the solution you'd like

How tab syncing works via the built in feature in Vivaldi, for example, is your browser syncs tabs to the cloud - and there is a menu where current tabs are listed per device. I can open that menu, pick a device, and open any tabs from any other device.
I'd really like to see Floccus work this way - even if it uses a folder in bookmarks (and corrosponding sub folders for each device) to do this instead of it's own menu. With tab sync and bookmark sync combined, this could easily be done by Floccus simply syncing the local tabs to it's corrosponding local bookmark sub-folder, and the bookmark sync would go ahead and sync that sub folder with the rest of the bookmarks. Doing it this way would have the added benefit of being able to open those current tabs from NextCloud on machines or browsers that do not have Floccus installed. Maybe I'm using someone else's PC, or maybe Im trying to accomplish something on a game console's browser and my PC has a tab open I need.

So in options for sync tabs, let me pick a local bookmark folder to sync to. It just pushes to that local folder (Tab Sync/HOSTNAME/ Or maybe /Tab Sync/Crappy Laptop). Then I can open it from any browser my bookmarks are synced to.
By letting the user decide what local folder, it also gives the option of letting me pick if I want those open tabs further sorted by browser (/Tab Sync/Crappy Laptop/FireFox)

Why not use Vivaldi's built it? I do, for now. But... It doesn't cover other browsers I use, and, more importantly, I'd be much rather having this data on MY server instead of thiers.

### Describe alternatives you've considered

Just using native tab syncing

**Comment by hellomiakoda** [comment]
I'll give it a try! I just did that on this laptop, and so far, it looks to do 
what I need it to do! Thank you! I can't donate while I'm out of work, but 
I've got Floccus on the list for when I'm back to work! ESPECIALLY if this 
works as expected!

**Comment by candrapersada** [comment]
`What you describe is already possible: You can create a tab sync account and select to sync with the same nextcloud account as your bookmarks, but instead of leaving the server folder blank, you enter a folder path where you want your tabs to end up on the server. I.e. when you sync your bookmarks root folder, you'll have a "Bookmarks Bar" folder in Nextcloud. Then you can set your tab sync to sync to /Bookmarks Bar/Tabs/My Device No 1 and the tabs will show up in your Bookmarks Bar under "Tabs" -> "My Device No 1"`

please explain in detail how to use `/Bookmarks Bar/Tabs/My Device No 1` it on google drive
