### ISSUE TITLE
[Android] search only finds results in the current folder (and its sub-folders)

### ISSUE THREAD

**Issue by heapifyman** [floccusaddon/floccus#1296]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.4.131 on Android 13

### Describe the Bug

The search only returns results from the currently selected bookmarks folder and its sub-folders.

Let's say you have a bookmark for `www.example.com` in folder `A` and folder `B`, which are both sub-folders of the `root` folder. If you then navigate to folder `B` inside the floccus Android App and then search for `example` the search results will only include the bookmark from folder `B`.

If the currently selected folder does not contain any bookmarks that match the search term, floccus will not display any results even if there are bookmarks in other folders that match the search term.

If however you are in the `root` folder the search results will include both the bookmark from folder `A` and the bookmark from folder `B`.

### Expected Behavior

The search should find results from all folders, not only the currently selected folder.

I would expect the search to return both bookmarks:

* `A/example.com`
* `B/example.com`

Regardless of where in the bookmarks folder structure I am at the moment.

### To Reproduce

*Steps to reproduce*

1. Organise bookmarks in different folders. For example, create folders `A` and `B` in the `root` folder, and add a bookmark for `www.example.com` to both folders `A` and `B`.
2. In floccus Android, navigate to folder `root/B`.
3. Tap into search field in the top bar, and search for `example`.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This is the intended behavior, not a bug. If you want to see results from all folders you need to search in the root folder. This should be apparent from the label for the search function which afaik says e.g. "Search in B..."
Do you have an idea on how to make this more apparent, perhaps?

**Comment by infinity0** [comment]
IMO this should not be the intended behaviour and the search box should just look in all accounts, and not change its behaviour. It should act similar to a browser address bar. No browser implements "search only in 1 bookmark functionality", likely because nobody needs it.

**Comment by dylandea** [comment]
> This is the intended behavior, not a bug. If you want to see results from all folders you need to search in the root folder. This should be apparent from the label for the search function which afaik says e.g. "Search in B..." Do you have an idea on how to make this more apparent, perhaps?

+1

Before reading your answer, I was also thinking:
 "I don't know if it was intended or not, but I think that's a good behavior".

It permits filtering and more precise queries, without creating a too complicated "Filtering" menu, or a dropdown with more details. 
If you want to search precisely you go to a precise subfolder, if you want to search everywhere you go to root.
Also, I've already seen this type of behavior elsewhere so it doesnt feel weird.
But I can imagine that some people get confused because this behavior is not explained explicitly.

It's true that browsers doesnt use this functionnality neither in the adress bar (but that's normal), neither in the Bookmarks menu, and to be honest I don't specially need it either.

However I can imagine how someone with 2000+ or more bookmarks could benefit from this, don't you think ?

Imagine this stuation:
I'm a crazy bookmark collector, with 5000 bookmarks. I'm a geek that jump between many OS.
I have a folder "MacOs Ventura"
A folder "MacOs Catalina"
A folder "Windows 11"
A folder "Windows 10"
A folder "Ubuntu"
A folder "ArchLinux"
A folder "Debian"
etc..

In each of these folders I have a folder called "Apps" or "Configs" or whatever.

So if I am searching for "Apps", I will have at least 7 results, without counting all the bookmarks with Apps in the URL or title.

So I can see how it could be useful, for someone with a lot of movies, a lot of classificxation standards.

So taking out this feature would be a loss, and 1 year from now, someone will come asking for this feature.

Another thought:
Either the current behaviour (better documented if possible), or some dropdown search results (ressembling the search dropdown in Github) with those options:

3 results found in this folder and subfolders:
-Apps (Folder)
-10 best apps for Windows 11 (Bookmark)
-Windows 11 apps you absolutely need (Bookmark)

56 results found everywhere:
-Apps (Folder) (in Windows 11)
-Apps (Folder) (in Windows 10)
-Apps (Folder) (in Macos)
-.......


But such Dropdown, with all those options, is starting to become difficult to create and maintain, no ?

So I think the current solution could be a middle solution between simplicity and precise searches.

**Comment by infinity0** [comment]
> honest I don't specially need it either.
> 
> However I can imagine how someone with 2000+ or more bookmarks could benefit from this, don't you think ?

UIs should be written to help the user execute the most common tasks faster. A rare task shouldn't be sped up at the expense of common tasks.

**Comment by marcelklehr** [comment]
IMO the current behavior is the typical behavior of a file manager which we are trying to mimick, but I understand that it can be confusing if the label is not fully legible

**Comment by infinity0** [comment]
Because of the lack of browser extensions on mobile, the floccus mobile UI should be trying to replace a browser address bar, and this is already a compromise.

I can't imagine anyone intentionally looking for a replacement for their browser bookmarks manager that acts more like a file manager. It's not a problem that I've heard anyone ever complain about, and it's certainly not why I was interested in floccus. Most people have 100,000s of files on their filesystem and trees up to 10 levels deep, but only several hundred or thousand bookmarks if that, with shallower trees.

I'm curious how often you personally use this folder-specific search functionality, vs wanting to just search across all bookmarks like in a normal browser.

**Comment by marcelklehr** [comment]
It's correct that this would mean changing a single line of code.

Let me please understand your perpspective a bit better. By default the behavior after opening the app is the one you want, AFAIU. You can search through all folders in the account you have selected. In order to get the selective folder filtering to apply, you need to select a subfolder first.

**Comment by infinity0** [comment]
> I know it's in that folder so I could navigate up to root and then down into folder "work" and open the bookmark directly. But that takes time.

+1, computers are about saving time, not just in terms of algorithms but in terms of human user time.

**Comment by marcelklehr** [comment]
Nice, thanks for the explanation! How about we have multiple search results sections? First section is results inside the current folder, second second is results inside the current account, third section is results in all other accounts?

**Comment by infinity0** [comment]
That sounds good to me yeah. Ideally the separator between the sections wouldn't take up too much screen space.
