### ISSUE TITLE
Login with Google Drive not working on Firefox

### ISSUE THREAD

**Issue by AstragoDE** [floccusaddon/floccus#1307]
### Which version of floccus are you using?

4.18.0

### Sync method

Google Drive

### Describe the Bug

Whilst trying to log in with my Google account, I get the following error message:

> Something went wrong
> Sorry, something went wrong there. Please try again.

This is the first login / account creation using floccus

### Expected Behavior

Login with Google Drive works and bookmarks get synced. 

### To Reproduce

Try to log in using Google. 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I cannot reproduce this offhand.

Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

**Comment by AstragoDE** [comment]
I am using the newest version (108.0.1) of Firefox on Windows (64 bit)

**Comment by marcelklehr** [comment]
Weird. I'm not on windows but I can log into google with floccus on firefox just fine.

**Comment by AstragoDE** [comment]
I don't know if it is any help, but I made a video of the process of trying to log in: [https://youtu.be/etQ_IsgIsxw](https://youtu.be/etQ_IsgIsxw). The app also seems to crash often when I try to log in using google Drive. It took me five attempts to log in without crashing the app. I use the latest release on Google Play and Android 13.

**Comment by marcelklehr** [comment]
Thanks for taking the time to record the video. A quick search didn't yield any promising results, except that other people seem to hit this error too at random with other OAuth apps :/

**Comment by AstragoDE** [comment]
I also have experienced this issue with the [violent monkey](https://github.com/violentmonkey/violentmonkey) extension, so there might be a problem with OAuth using extensions in general.

**Comment by tjorim** [comment]
For what it's worth, just downloaded the latest Android app from Play Store and choosing Google Drive immediately crashes the app. I submitted the log with the feedback window that pops up.

**Comment by kaiminz** [comment]
kiwi browser， 107， Android9， login in Gdrive does not work， neither.

**Comment by marcelklehr** [comment]
> https://*.extensions.allizom.org/ 

Firefox is supposed to recognize that URL and redirect to the addon instead of trying to load it from the web. Are you using an official build of firefox?

**Comment by AstragoDE** [comment]
I am using an official build on the newest version. Unfortunately, I still get the error.

**Comment by AstragoDE** [comment]
Since the problem has not been resolved yet, I am writing this comment to prevent the bot from closing the issue.

**Comment by peter-kehl** [comment]
Thank you for Floccus.

The same Google Auth problem here. Current Firefox 115.0.2 (as distributed by Manjaro, a stable sister of Arch Linux).
- "No accounts here"
- + "New account"
- https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?client_id=305459871054-ALPHANUMSHERE.apps.googleusercontent.com&response_type=code&redirect_uri=https%3A%2F%2ALPHANUMSHERE.extensions.allizom.org%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&approval_prompt=force&access_type=offline&code_challenge=ALPHANUMSHERE&state=ALPHANUMSHERE&service=lso&o2v=1&flowName=GeneralOAuthFlow
- (I have two Google accounts; I choose my first one)
- "allizom.org wants access to your Google Account"
- -> https://accounts.google.com/info/unknownerror
- Something went wrong
  Sorry, something went wrong there. Try again.

![image](https://github.com/floccusaddon/floccus/assets/4270240/5c2ba838-25a7-412a-a66b-88e3f5acd93c)

I do have (current) Violent Monkey (the above screenshot was with Violent Monkey enabled), and I do use many Firefox extensions, but (so far) they never caused any Google Auth problem. Anyway, I've disabled Violent Monkey, the problem is still here. Please advise.

**Comment by TonyRL** [comment]
@peter-kehl Do you use [ClearURLs](https://github.com/ClearURLs/Addon)? It does interferes with OAuth https://github.com/ClearURLs/Addon/issues/258, https://github.com/ClearURLs/Addon/issues/329.
