### ISSUE TITLE
Syncing doesn't not working as expected - keeps resyncing deleted stuff back from other devices. 

### ISSUE THREAD

**Issue by Stifler6996** [floccusaddon/floccus#1376]
### Which version of floccus are you using?

4.19.1 chrome addon on several devices (x64 and arm64) 

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Opera GX (core: 97.0.4719.84 - Chrome base:111.0.5563.147).  Google Chrome: 111.0.5563.66

### Which version of Nextcloud? (if relevant)

25.0.4

### Describe the Bug

1: From one pc, open browser. Floccus set to merge ( `Merge changes with changes from other browsers` )
2: Delete some bookmarks.
3: close browser, once sync is complete.
4: From another pc, open browser. Floccus also set to merge.
5: wait for sync to occur.
6: close browser when complete.
7: go back to first pc open browser.
8: wait for sync.
9: note the deleted items are back, since they were on the other device, and it synced up, instead of down.

I don't know how the program works, but I would have figured there were timestamps on when bookmarks were added, so when devices sync in "merge" mode, they would know which changes are newer from other devices.

### Expected Behavior

If I delete a bookmark on one browser, I'd expect it to be deleted when another broswer sync. Not for to be restored.

### To Reproduce

1: From one pc, open browser. Floccus set to merge ( `Merge changes with changes from other browsers` )
2: Delete some bookmarks.
3: close browser, once sync is complete.
4: From another pc, open browser. Floccus also set to merge.
5: wait for sync to occur.
6: close browser when complete.
7: go back to first pc open browser.
8: wait for sync.
9: note the deleted items are back, since they were on the other device, and it synced up, instead of down.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by Stifler6996** [comment]
I also have the android app installed, which I believe I had forced stopped. However, for completeness the floccus android app is version v4.19.0

The other thing to note, I can "fix" the problem, by forcing direction of sync - on all devices (IE set all devices to down only, and on the device I add the bookmark with, I force up, and wait).
Its just a little annoying since I add/manage bookmarks from several pc, and my android phone, and need to flip this back and forth.

**Comment by daffydock** [comment]
Experiencing same problem but with Tabs. It began seemingly yesterday on my machines. In my case, it even happens on the same machine Re: tabs. 

Case in point: Already closed tab --it seems to only happen with one tab-- reappears on same PC upon sync. I noticed this happen in two separate/different machines. Each doing this with their own separate Tabs. that is to say, the same tab does not appear on all machines. Likely due to the fact that each machine has its own, separate Tab folder. 

I sync both tabs and bookmarks but noticed this only with Tabs. However, when I have a chance I will check on Bookmarks as well. Since I only noticed this happen recently. 

Also notice that there was a recent update for NC Bookmarks app. Assuming Floccus has not broken something, perhaps something did get broken after updating and they are not playing nice with each other. Albeit I am not sure yet. 

Issue seems to be fixed, at least in the short term with activating an upstream sync. Starting a down or merge sync only recreates the tab.

**Comment by marcelklehr** [comment]
@daffydock That's a known limitation of the tab sync, since browsers do not keep persistent tab IDs.

**Comment by marcelklehr** [comment]
@Stifler6996 I cannot reproduce this. This is a very basic sync scenario that is even covered in the integration tests. I think iff this is a bug in floccus, the steps to reproduce are more complex.

**Comment by Stifler6996** [comment]
Okay, I will attempt to investigate more. I will ensure that the mobile app is out of the equation. I'm wondering if I in fact left both browsers open and one was beating the other to the sync.

Anyhow, I will test again.

**Comment by Stifler6996** [comment]
Okay, I cannot reproduce with a new bookmark. It seems to work fine. I can only surmise there may have been a problem around the bookmarks that I was originally attempting to delete. They were really, very old bookmarks from probably around 2018. I've been running Nextcloud and this addon since around then (keeping them updated).

Unfortunately I would have to roll back from a backup in order to test with those bookmarks again, something not worth the effort for what seems to be an exception.

Sorry for the inconvenience.

**Comment by daffydock** [comment]
> @daffydock That's a known limitation of the tab sync, since browsers do not keep persistent tab IDs.

So, what you are saying is that if I pin a tab that it will constantly re-spam that tab in other sync instances in different browsers/PCs? Forever? Unfortunately, I cannot recall if the issue I had were with specifically pinned tabs. Since I usually do not need to pin tabs since I usually keep the count of tabs on the low end out of habit, and the ones I noticed the issue with before where not pinned. Albeit, I am not currently 100% certain if the were pinned or not. Since the issue happens sporadically, albeit it has been a while and when it did happen, I would without thinking just immediately do an up sync to fix it. As I would not have time to troubleshot it, then. 

Albeit I have noticed that it has not happened in a while. Will keep an eye if it happens again.
