### ISSUE TITLE
WebDAV: Keep a set of previous xbel file versions for backup purposes

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#146]

**Comment by jlbprof** [comment]
Are you suggesting a rolling set, like xbel, xbel.1, xbel.2 ... xbel.N and
rotate them?

**Comment by marcelklehr** [comment]
@jlbprof Something like that, but it's not really important. It was suggested in the beta-testing issue and I thought it was a cool idea.

**Comment by DJCrashdummy** [comment]
nice idea, but if your webdav-backend already supports visioning wouldn't that be rather counterproductive?

**Comment by jlbprof** [comment]
I am not sure what you mean, it does not version.  It always works with the
xbel file you enter into the options page.  If you change the name of the
file you will have a 2nd copy.   Of course you could copy the xbel file
anywhere you want and go back to an old one at anytime.

**Comment by DJCrashdummy** [comment]
@jlbprof for example nextcloud (but still talking about webdav) supports versioning and you can access and revert them by a simple click (no need for manual copying & renaming): https://docs.nextcloud.com/server/13/user_manual/files/version_control.html

in case of backend-versioning:
- the backups of bookmarks.xbel may get doubled by floccus and the backend... (not a huge problem, but also not a nice behaviour :slightly_frowning_face: )
- but if names like `xbel, xbel.1, xbel.2 ... xbel.N` are used, it gets even worse because all of them will probably get backup by the backend after changing/renaming them. - to avoid this a timestamp for the name would be better, since therefore the file is just created once, never touched and deleted after a while.

--> probably if implementing this, making it optional and making it choosable how much versions should be kept is a good idea.
