### ISSUE TITLE
Firefox v120, unable activate "login with google"

### ISSUE THREAD

**Issue by ivanmmz** [floccusaddon/floccus#1468]
### Which version of floccus are you using?

5.0.2

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Describe the Bug

Whatever in Mac or Win, firefox v120 is not support floccus, by import the jason files or login to google

### Expected Behavior

it should able to import the jason files or login to google

### To Reproduce

https://github.com/floccusaddon/floccus/assets/65158038/3c933495-99c4-4b3e-a2e4-b96379bf80cd

### Debug log provided

- [ ] I have provided a debug log file

**Comment by bhlevca** [comment]
It is not only Firefox 120. The same issue is present in Firefox  115. I am under the impression that if the plugin was there  before it will work. But adding the plugin again or a new one it will not work. It has something to do with the communication with Google. It may have something to do with what Mozilla is doing with add ons. It may be that it require to be added to their list of approved add ons.

**Comment by dcanl** [comment]
Hello,

Here is console trace when clicking on the "login with google" button:

`Error: Type error for parameter permissions (Error processing origins.0: Value "https://oauth2.googleapis.com" must either: be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/) for permissions.contains.
    F moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    l moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    l moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    a moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    promise callback*p moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    s moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    s moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    authorize moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    loginGoogleDrive moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    Te moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    n moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    Te moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    $emit moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    click moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    Te moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    n moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
    _wrapper moz-extension://d8b95ac4-ed74-4316-91ff-d07c3aea2a24/dist/js/options.js:2
options.js:2:2185795`

Too bad, I just switched to Firefox because of future of Google Chrome extensions policies (manifest v3, disabling manifest v2). I hope you will quickly fix that! 🙂

Importing account is not working either, see #1464.

**Comment by bhlevca** [comment]
This has worked exactly one day. Today it doesn't work. I wonder what has changed since yesterday?
