### ISSUE TITLE
Cannot create a profile in Mullvad Browser

### ISSUE THREAD

**Issue by alpo** [floccusaddon/floccus#1509]
### Which version of floccus are you using?

5.0.6

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Mullvad Browser 13.0.7 (based on Mozilla Firefox 115.6.0esr)

### What kind of WebDAV server are you using? (if relevant)

Caddy

### Describe the Bug

When I enter the WebDAV URL, user name and password and press the CONTINUE button I got a red message "Cannot request origin permission for `*://*/*` since it was not declared in the manifest" under the URL.

### Expected Behavior

Profile creation continues.

### To Reproduce

Press the "NEW PROFILE" button.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This should be fixed in v5.0.9

**Comment by alpo** [comment]
The same behavior for v5.0.9

**Comment by marcelklehr** [comment]
Then it's likely a Mullvad issue

**Comment by alpo** [comment]
Do you test your add-on in Tor Browser? The Mullvad Browser and Tor Browser are essentially the same build of the Firefox, but the MB does not include Tor.

**Comment by marcelklehr** [comment]
> Do you test your add-on in Tor Browser?

I do not

**Comment by ruihildt** [comment]
Quickly parsing the manifest, it seems the floccus webextension relies on service workers.

Service workers are not currently not working in Private Browsing Mode (https://bugzilla.mozilla.org/show_bug.cgi?id=1320796), which Mullvad Browser uses by default.

**Comment by bhlevca** [comment]
I don't think that this issue is a private browsing mode issue. You can disable that in Mulvadd browser and you get the exact same problem. I experimented with various settings in the browser including disabling all the security features that could be disables and I could not make it work.  There may be a JavaScript issue, but I don't know what floccus does. In any case Trying Google bookmarks is frozen completely like it happened in 5.0.6 in Firefox.  Marcel Fixed something then for Firefox, perhaps this issue is related.

**Comment by supercoolspy** [comment]
Not fixed in librewolf either

**Comment by ruihildt** [comment]
If it's not private browsing mode, it's likely to be some RFP (Resist Fingerprinting) settings. I don't have the time to look further into it right now though.

**Comment by bhlevca** [comment]
> If it's not private browsing mode, it's likely to be some RFP (Resist Fingerprinting) settings. I don't have the time to look further into it right now though.

you are probably right

**Comment by MangoCubes** [comment]
One thing I noticed is that the syncing works if it is imported instead of creating the profile directly in the Mullvad browser. So a workaround is to create a profile in Firefox, export it, and import it in Mullvad browser. Settings can be updated directly after you import it. Only minor issue is that the "Last synchronized" message does not update whilst the add-on screen is open, so it looks like nothing is happening when you manually trigger synchronisation.

**Comment by marcelklehr** [comment]
> the syncing works if it is imported instead of creating the profile directly in the Mullvad browser.

This was the clue. Should be fixed with the next release.
