### ISSUE TITLE
file:// URLs in tabs cause synchronization failures

### ISSUE THREAD

**Issue by unode** [floccusaddon/floccus#1627]
### Which version of floccus are you using?

5.1.4

### How many bookmarks do you have, roughly?

~300

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 125.0.3

### What kind of WebDAV server are you using? (if relevant)

Owncloud 10.14.0

### Describe the Bug

Synchronizing tabs after opening a pdf in Firefox ([click example](https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf) and "Open with Firefox") causes an `Illegal URL` error.
When opening the PDF directly in the browser, the URL looks like `file:///tmp/mozilla_username0/filename.pdf` causing the error when synchronized to another browser.

### Expected Behavior

The `file://` URL should be used as-is. If pointing to a file that doesn't exist, the equivalent 404 page should be shown.
If the `file://` actually exists on disk on all synchronized browsers, it should simply restore the tab and open the existing file.

### To Reproduce

1. Visit https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf
2. Click in "Open with Firefox" which should make the PDF open in Firefox using `pdf.js`.
3. The URL should contain file://`
4. Synchronize tabs using floccus.
5. In the second browser synchronize tabs. You should see the Debug error.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by khankul** [comment]
Still present as of Floccus 5.2.5, using Git. The problem with that error is that when encountering file links, it goes into a cycle of trying to open the last batch of tabs it was working on, resulting in multiple duplicates, whose number rises pretty fast. Since it queries the sync attempts one after another, it can only be stopped at once by removing the profile. My current remedy is to remove the file links from the XBEL file, and sync manually to prevent file links from ending up in it.

**Comment by marcelklehr** [comment]
I can confirm this is a limitation of the tabs API on firefox:

> For security reasons, in Firefox, [the URL for new tabs] may not be a privileged URL.

Will have to do what you currently do manually: Filter out the privileged URLs :/
