### ISSUE TITLE
Permission or Documentation Problem: Browser History Access Requested

### ISSUE THREAD

**Issue by gohrner** [floccusaddon/floccus#1637]
### Which version of floccus are you using?

5.2.0.3

### How many bookmarks do you have, roughly?

50

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium

### Which version of Nextcloud Bookmarks are you using? (if relevant)

--

### Which version of Nextcloud? (if relevant)

--

### What kind of WebDAV server are you using? (if relevant)

Apache httpd

### Describe the Bug

Today, Floccus was blocked by Chromium, as it seems to require an additional permission:

![image](https://github.com/floccusaddon/floccus/assets/26199042/2590058b-e594-48a0-a227-bde35bd3c0ae)

I didn't find info about it in the release notes, and this new permission is not documented:

https://floccus.org/guides/

```plain
Permission	Explanation
storage, unlimitedStorage	Necessary for maintaining a cache and mappings between server and browser bookmarks
alarms	Necessary for triggering synchronization in regular intervals
bookmarks	Necessary for creating and reading bookmarks
Unlimited web access	Necessary for accessing your self-hosted server. This cannot be limited, because everybody's server has a different URL. Unfortunately, the way webextensions work currently, floccus also gets access to all the data the browser has collected on those websites. However, floccus makes no use of that data and doesn't in any way collect information about you.
identity	Necessary for connecting with Google Drive
```

So I wondered if this is legit - it probably is, but there also have been more than enough reports of hijacked extensions (or whole Open Source projects, see `liblzma`), so I wanted to be sure.

### Expected Behavior

New permissions required to use the browser extension should be documented and also mentioned in the release notes.

### To Reproduce

I really didn't do anything and it broke, so I assume it's sufficient to install an older release of the Floccus Chromium extension and let the auto-update do its job.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Ah, I'm sorry for the lack of documentation. I've updated the website and the release changelog: https://github.com/floccusaddon/floccus/releases/tag/v5.2.0

**Comment by BloodyIron** [comment]
That doesn't include the v5.2.0.3 sub-version though. And what's up with this aspect? (it can now) "read and change all your data on all websites".

I'm re-enabling it myself, but making these aspects forced and not optional is concerning to me. Something like this should be off by default and an option I can choose to enable. Is that not possible here?

As in, I probably care about the click history stuff, that sounds useful. But the... "change all your data on all websites" part, really do want to see an explanation on that please.

**Comment by marcelklehr** [comment]
> That doesn't include the v5.2.0.3 sub-version though

So, due to technical limitations, v5.2.0.3 is the same as v5.2.0; v5.2.0.{0-2} were beta versions.

> read and change all your data on all websites

This has always been there. I wrote it down as "Unlimited web access". Due to how browsers implement this I can only ask for one permission to both *send requests to all possible web hosts* as well as *read and change data on all websites*. There is no distinction.

**Comment by BloodyIron** [comment]
> > That doesn't include the v5.2.0.3 sub-version though
> 
> So, due to technical limitations, v5.2.0.3 is the same as v5.2.0; v5.2.0.{0-2} were beta versions.
> 
> > read and change all your data on all websites
> 
> This has always been there. I wrote it down as "Unlimited web access". Due to how browsers implement this I can only ask for one permission to both _send requests to all possible web hosts_ as well as _read and change data on all websites_. There is no distinction.

1. Thanks for clarifying on the versioning, I see how that comes to be. Maybe make the "release" version (next time?) match the non-beta version to avoid confusion? :P So in this case in the releases section I'd think it reasonable to see v5.2.0.3 so that I know it matches what I'm running on my compie. I don't _necessarily_ need to see the beta versions in the "releases" section of github, but the "prod" style versions would be appreciated in general please. :)
2. I hear you on the limited options on your end, and appreciate you clarifying on that. I don't think you necessarily inappropriately communicated the state of things in the release notes, just due to the nuances you just described there was a touch of alarm in my experience. And yeah it sounds like your options are rather limited, I empathise with your side of that.

Thanks for clarifying on all that and continuing your work on this tool! I love this extension and use it constantly on multiple computers. Yay! :D
