### ISSUE TITLE
Android app slows down

### ISSUE THREAD

**Issue by cookire** [floccusaddon/floccus#1674]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

600

### Are you using other means to sync bookmarks in parallel to floccus?

Yes, google sync

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

126, google Chrome 

### Describe the Bug

App slows down when trying to open folders with 50+ bookmarks

### Expected Behavior

Not slowing down

### To Reproduce

Open a bookmark folder on Android with 50+ bookmarks

### Debug log provided

- [ ] I have provided a debug log file
Thanks for the fantastic app !!

**Comment by marcelklehr** [comment]
Hi @cookire 

This is more or less known. The mobile app is currently not very performant. As long as it is Mozilla's goal to bring the bookmarks API to Firefox for Android, I'm not committed to investing significant work into the mobile app because it would be wasted once Floccus works on Firefox for Android. I'm closing this for now as I'm already aware of the performance problems with the mobile app. Thank you for your feedback nonetheless :)
