### ISSUE TITLE
Please solve annoying sync in getting back focus of floccus!

### ISSUE THREAD

**Issue by IngoBelka** [floccusaddon/floccus#1704]
### Which version of floccus are you using?

5.2.6

### How many bookmarks do you have, roughly?

150

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

FF 129

### Which version of Nextcloud? (if relevant)

27.1.8

### Describe the Bug

Like mentioned right in other posts floccus is starting synchronization each time it gets back the focus. In addition it floods the waste basket of my NC with a great amount of *.lock files. 
I did set no automatic sync and sync intervall to one time a day.

### Expected Behavior

Sync like set. 

### To Reproduce

1. start floccus
2. start another app
3. switch back to floccus
4. see floccus synching

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @IngoBelka 
I understand that this issue is annoying and you would like to have it solved as soon as soon as possible, but please don't spam the issue tracker with duplicate issues. It just creates more overhead for me. I'm aware of the issue and will fix it as soon as I can. Thank you for your understanding.
