### ISSUE TITLE
Falsely removing added bookmarks on sync after error

### ISSUE THREAD

**Issue by RonMatGH** [floccusaddon/floccus#898]
### Describe the bug
I'm using sync strategy "Merge" using my own WebDAV server.
When I add one or more bookmarks in my sync folder, floccus shows the following error message at next sync:
"E018: Couldn't authenticate with the server."
When I re-initiate the sync (e.g. Sync Now button) the recently added bookmarks is removed.  

### To Reproduce
1. Add a bookmark in the sync folder
2. Click "Sync Now"
3. When error message appears repeat step 2
4. Bookmark is removed instead to of being uploaded to the server.

### Expected behavior
Upon sync the locally added bookmarks should be uploaded to the server.

### Screenshots
![image](https://user-images.githubusercontent.com/34383577/124281012-98f1a180-db49-11eb-8bdc-f7a23540524f.png)

### Desktop
 - OS: Windows 10 Pro (64-bit) 21H1
 - Browser: Firefox
 - Browser Version: 89.0.2 (64-bit)
 - Floccus version: 4.6.4
 - Floccus sync method: webdav

### Server
 - Model: Synology DiskStation DS918+
 - OS: Synology DiskStation Manager (DSM) 6.2.4-25556

### Debug log
First sync, with error message:
[floccus-4.6.4-2021-07-02.log-8.txt](https://github.com/floccusaddon/floccus/files/6754846/floccus-4.6.4-2021-07-02.log-8.txt)

Second sync, falsely removing the locally added bookmark:
[floccus-4.6.4-2021-07-02.log-9.txt](https://github.com/floccusaddon/floccus/files/6754850/floccus-4.6.4-2021-07-02.log-9.txt)

### Additional context
I noticed that my sync file on the server show Jun  9 as the last modification date. Has the add-on been updated around this date? Maybe this helps.

**Comment by marcelklehr** [comment]
Hey @RonMatGH 

This seems not to be due to floccus. Last release was Apr 24 2021.


<details>
<summary>
If you're up for some debugging, try this.</summary>

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

</details>

You can also try to replicate the HTTP request that floccus does to save the file in your webdav share:

``` 
curl -X PUT --user "username:password" -T '/path/to/local/file.xbel' https://your/url/to/file.xbel
```

**Comment by marcelklehr** [comment]
The peculiar thing is that the sync did not fail earlier. There's a number of requests before any syncing is done that should have failed as well, preventing any wrong bookkeeping.
