### ISSUE TITLE
Cannot add empty mapping 

### ISSUE THREAD

**Issue by vatolin** [floccusaddon/floccus#964]
### Describe the bug
After latest update I can not use Floccus due to an error mentioned as »Cannot add empty mapping«.

### To Reproduce
1. Go to Firefox 92
2. Click on the Floccus Icon in the head of the window
3. See the error message in a red box.
4. Click on the button - German system - [Jetzt synchonisieren]
5. The error message re-appears.

### Expected behavior
It should sychronize the bookmarks with my Nextcloud server.

### Screenshots
![Bildschirmfoto 2021-09-23 um 20 31 16](https://user-images.githubusercontent.com/50046359/134564685-dfc7f956-ed8b-47ae-a414-e477a02edf1d.png)

### Desktop
(please complete the following information)
 - OS: macOS 11.6
 - Browser Firefox
 - Browser Version 92
 - Floccus version: [e.g. 4.8.0]
 - Floccus sync method: WebDAV
 - 
### Server
(please complete the following information)
 - OS: Debian
 - Nextcloud version: 21.0.4
 - Bookmarks app version: 10.0.0

Cannot add logfile because it's too long.

**Comment by marcelklehr** [comment]
Hello @vatolin

I'm sorry for the inconvenience. You can try

1. Making a backup of your bookmarks (e.g. by exporting them)
2. Going to your floccus account settings and clicking "trigger sync from scratch"
3. Click save
4. Trigger another sync run
5. Make sure all your bookmarks are the way they should be

**Comment by Aldjinn** [comment]
I've encountered the same issue. I was able be removing the "Mobile Lesezeichen" and "Mobile Bookmarks" folders on my Nextcloud and push the bookmarks to the server again.

**Comment by pretentious7** [comment]
Same issue here. sync from scratch doesn't make it go away either.

**Comment by marcelklehr** [comment]
Debug logs of the error would be helpful. Can you upload a debug log of the error over here: cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

**Comment by joergRossdeutscher** [comment]
I had the same issue and fixed it. Current Vivaldi, current MacOS vs. current Kiwi on Android. The issues occured when I updated the Mac to 4.8 , the Playstore still is on 4.7, so I did not update the Phone.

I had inconsistent settings for the option “Schliesse den lokalen Ordner dieses Kontos… aus“ (exclude local folder), because I never understood what this option means at all.  For some reason this was INcluded on Smartphone and EXcluded on computer.

Now, having this issue, I think I understood what this option means. It's about the “Mobile Bookmarks“ folder on the phone to sync or not. Hell, no, I don't even use it. :-) 

- I sync the „root“ on both devices
- I don't use local folders, I just want identical stuff on phone and computer
- My smartphone was including „Mobile Bookmarks“ folder in the upload
- My computer was not able to create “Mobile Bookmarks“ in the root, because this is not possible in my structure: My bookmarks are directly in the „root“, there is no possibility to create a mobile folder “above“

I tried to fix this by excluding the mobile folder on the smartphone and choosing a “send to server“-sync, but having a look at the xbel-file there, the file still included „Mobile Bookmarks“.

I set both devices to EXclude local folders, then I edited the xbel-file directly on the server and removed the „Mobile Bookmark“ directly from the xbel-File, then did a downsync on both devices. This was succesful. Then I set both devices back to normal sync, and it still worked.

Beside some fix, kindly I suggest to change the description of the option “exclude local nested folders“. It was written by a person that totally understands what's going on and tried to explain it 100% technical correct. For me was totally unclear what's “Include or exclude a local folder“.

**Comment by marcelklehr** [comment]
It does seem like this is related to the mobile bookmarks folder. Also see #831

**Comment by marcelklehr** [comment]
> It was written by a person that totally understands what's going on and tried to explain it 100% technical correct. For me was totally unclear what's “Include or exclude a local folder“.

I can definitely use help on the wording of some of the more complex settings. If you'd like to help come up with better ones, feel free to open issues or a pull request :hearts: 

For now, I've changed the wording to this:

> You can nest accounts so that a parent folder belongs to account A and a sub folder to account A and B. Do you want to allow other accounts to sync this account's folder as well?

**Comment by joergRossdeutscher** [comment]
Hello & good morning, yes, I think the new wording is much better. Thanks for clarifying this.

About my bookmarks folder structure: I am pretty fine if this is an edge case and gets sorted out. My idea is just, that I do not differ between „Bookmarks folder“, „Bookmarks bar“ and „Mobile Bookmarks“. I want the same bookmarks on every device, and on desktop I want the root folder also as the bookmark bar. 

In all of my browsers I can configure which folder is chosen for that specific function, so I chose the root everywhere. MobileBookmarks=BookmarkBar=root

If this is an edge case, feel free to ignore it. Just wanted to help fixing the issue.
